import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  CreateDateColumn,
  JoinColumn,
  Unique,
} from 'typeorm'
import { Exclude } from 'class-transformer'
import { ApiProperty } from '@nestjs/swagger'
import { User } from 'src/users/entities/user.entity'
import { ToNumber } from 'src/common/decorators/to-number.decorator'

export enum StoreTier {
  Starter = 'Starter',
  Growth = 'Growth',
  Pro = 'Pro',
  Advanced = 'Advanced',
  Ultimate = 'Ultimate',
}

export const StoreTiers = {
  Starter: { subscriptionPrice: 5, productsLimit: 10, adminsLimit: 1 },
  Growth: { subscriptionPrice: 10, productsLimit: 20, adminsLimit: 2 },
  Pro: { subscriptionPrice: 25, productsLimit: 35, adminsLimit: 3 },
  Advanced: { subscriptionPrice: 35, productsLimit: 70, adminsLimit: 4 },
  Ultimate: { subscriptionPrice: 60, productsLimit: 180, adminsLimit: 7 },
} as const

@Entity()
@Unique(['userId'])
export class Store {
  @ApiProperty({ description: 'Unique identifier for the store' })
  @PrimaryGeneratedColumn()
  id: number

  @ApiProperty({ description: 'ID of the user who owns this store' })
  @Column({ type: 'int' })
  userId: number

  @Exclude()
  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn()
  user: User

  @ApiProperty({ description: 'Name of the store' })
  @Column({ type: 'varchar', length: 255 })
  name: string

  @ApiProperty({ description: 'Description of the store', type: String, nullable: true })
  @Column({ type: 'text', nullable: true })
  description: string | null

  @ApiProperty({ description: 'Logo URL of the store', type: String, nullable: true })
  @Column({ type: 'varchar', length: 500, nullable: true })
  logoUrl: string | null

  @Exclude()
  @Column({ type: 'varchar', length: 255, nullable: true })
  logoKey: string | null

  @ApiProperty({ description: 'Currency symbol used by the store' })
  @Column({ type: 'varchar', length: 10 })
  currencySymbol: string

  @ApiProperty({ description: 'Subscription level of the store', enum: StoreTier })
  @Column({ type: 'enum', enum: StoreTier, default: StoreTier.Starter })
  tier: StoreTier

  @ApiProperty({ description: 'Total revenue generated by the store' })
  @ToNumber()
  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  totalRevenue: number

  @ApiProperty({ description: 'Total claimed referral earnings in USD' })
  @ToNumber()
  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  claimedReferralEarning: number

  @ApiProperty({ description: 'Unique referral code for the store', type: String, nullable: true })
  @Column({ type: 'varchar', length: 50, nullable: true })
  referralCode: string | null

  @ApiProperty({ description: 'Timestamp of first successful payment', type: Date, nullable: true })
  @Column({ type: 'timestamp', nullable: true })
  firstPaymentMadeAt: Date | null

  @ApiProperty({ description: 'Indicates if the store is active' })
  @Column({ type: 'boolean', default: true })
  isActive: boolean

  @ApiProperty({ description: 'Store that referred this store', type: Number, nullable: true })
  @Column({ type: 'int', nullable: true })
  referredByStoreId: number | null

  @Exclude()
  @ManyToOne(() => Store, { onDelete: 'SET NULL' })
  @JoinColumn()
  referredByStore: Store | null

  @ApiProperty({
    description: 'Timestamp when the store active plan will expire',
    type: Date,
    nullable: true,
  })
  @Column({ type: 'timestamp', nullable: true })
  expiresAt: Date | null

  @ApiProperty({ description: 'Indicates if the store has been soft-deleted' })
  @Column({ type: 'tinyint', default: 0 })
  isDeleted: boolean

  @ApiProperty({ description: 'User ID of the creator', type: Number, nullable: true })
  @Column({ type: 'int', nullable: true })
  createdById: number | null

  @Exclude()
  @ManyToOne(() => User, { onDelete: 'SET NULL' })
  @JoinColumn()
  createdBy: User | null

  @ApiProperty({ description: 'Date and time the store was created' })
  @CreateDateColumn({ type: 'timestamp' })
  createdAt: Date

  @ApiProperty({
    description: 'ID of the user who last updated the store',
    type: Number,
    nullable: true,
  })
  @Column({ type: 'int', nullable: true })
  updatedById: number | null

  @Exclude()
  @ManyToOne(() => User, { onDelete: 'SET NULL' })
  @JoinColumn()
  updatedBy: User | null

  @ApiProperty({
    description: 'Timestamp when the store was last updated',
    type: Date,
    nullable: true,
  })
  @Column({ type: 'timestamp', nullable: true })
  updatedAt: Date | null

  @ApiProperty({
    description: 'User ID of the person who deleted the store',
    type: Number,
    nullable: true,
  })
  @Column({ type: 'int', nullable: true })
  deletedById: number | null

  @Exclude()
  @ManyToOne(() => User, { onDelete: 'SET NULL' })
  @JoinColumn()
  deletedBy: User | null

  @ApiProperty({ description: 'Timestamp when the store was deleted', type: Date, nullable: true })
  @Column({ type: 'timestamp', nullable: true })
  deletedAt: Date | null

  @ApiProperty({
    description: 'User ID of the person who restored the store',
    type: Number,
    nullable: true,
  })
  @Column({ type: 'int', nullable: true })
  restoredById: number | null

  @Exclude()
  @ManyToOne(() => User, { onDelete: 'SET NULL' })
  @JoinColumn()
  restoredBy: User | null

  @ApiProperty({ description: 'Timestamp when the store was restored', type: Date, nullable: true })
  @Column({ type: 'timestamp', nullable: true })
  restoredAt: Date | null
}
