import { ApiProperty } from '@nestjs/swagger'
import { ToNumber } from 'src/common/decorators/to-number.decorator'

export class StoreAnalyticsResponseDto {
  @ApiProperty({ description: 'Total revenue generated by the store' })
  @ToNumber()
  totalRevenue: number

  @ApiProperty({ description: 'Number of pending orders in the store' })
  @ToNumber()
  pendingOrders: number

  @ApiProperty({ description: 'Number of active non-admin users in the store' })
  @ToNumber()
  activeUsers: number

  @ApiProperty({ description: 'Number of active products currently available in the store' })
  @ToNumber()
  activeProducts: number

  @ApiProperty({ description: 'Number of active store admins' })
  @ToNumber()
  activeAdmins: number
}
